baseURL = 'http://example.org/'
languageCode = 'es-ES'
title = 'My New Hugo Site'
theme = "shadocs"

defaultContentLanguage = "en"

[Languages]
    [Languages.en]
        title = "Mister Hugo"
        weight = 1
        languageName = "English"
        contentDir = "content/en"
   [Languages.fr]
        title = "Monsieur Hugo"
        weight = 2
        languageName = "Français"
        contentDir = "content/fr"
    [Languages.es]
        title = "Señor Hugo"
        weight = 3
        languageName = "Español"
        contentDir = "content/es"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 10
  [markup.goldmark.renderer]
    unsafe = false
