baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "shadocs"

defaultContentLanguage = "en"

[Languages]
    [Languages.en]
        title = "Mister Hugo"
        weight = 3
        languageName = "English"
        contentDir = "content/en"
   [Languages.fr]
        title = "Monsieur Hugo"
        weight = 1
        languageName = "Français"
        contentDir = "content/fr"
    [Languages.es]
        title = "Señor Hugo"
        weight = 2
        languageName = "Español"
        contentDir = "content/es"

[params]
  toc = false


